name: run extract.py

on:
  push:
    paths:
      - 'extract.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-bigquery duckdb

      - name: Set up Google Cloud Credentials
        run: echo "$GCP_SA_KEY" > magicalytics.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Set Google Application Credentials
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/magicalytics.json" >> $GITHUB_ENV
      
      - name: Run the extraction script
        run: python extract.py
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}

      - name: Commit and push the log file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add script_report.txt
          git commit -m "Update logs" -a
          git push
