name: Fetch and Process Data from BigQuery

on:
  push:
    branches:
      - main

jobs:
  fetch-and-process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Authenticating with Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Setting up Google Cloud SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Set up Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install google-cloud-bigquery duckdb

      # Execute the extract.py script
      - name: Run ETL process
        run: |
          export MD_TOKEN=${{ secrets.MD_TOKEN }}
          python extract.py

      # Optionally: Upload the log file as artifact
      - name: Upload log file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: script-log
          path: script_report.txt
